backend:
  name: git-gateway
  branch: main

site_url: "https://rainbow-narwhal-dd10ae.netlify.app"
display_url: "https://rainbow-narwhal-dd10ae.netlify.app"
logo_url: "https://rainbow-narwhal-dd10ae.netlify.app/logo.png"

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titel", widget: "string" }
      - { name: "date", label: "Datum", widget: "datetime" }
      - { name: "body", label: "Inhalt", widget: "markdown" }

